### ISSUE TITLE
Don't dim unfocused monitors.

### ISSUE THREAD

**Issue by Earnestly** [Cloudef/orbment#10]
I'm writing this just as a note for others.  Currently dimming is hardcoded as a workaround for not having (server-side) client borders.

This means that when watching a video stream or otherwise on a second monitor while working on the main monitor it will be dimmed.

I suggest as a workaround for this to simply not dim any non-focused monitors.  The disadvantage of this approach is people won't have dimmed secondary monitors if it was necessary.

**Comment by boomshroom** [comment]
My second (and sometimes first if I'm working with the second one) turning also always startles me whenever it happens. Dimming might be a good idea, but currently it puts the entire monitor to sleep until I switch focus.

**Comment by Cloudef** [comment]
Dimming is not related to sleep. That's DPMS which you can turn off with WLC_IDLE_TIME=0, you can also remove dimming with WLC_DIM=1 see <https://github.com/Cloudef/wlc> more.
