### ISSUE TITLE
Enable tap on click

### ISSUE THREAD

**Issue by onny** [Cloudef/orbment#103]
Hi,
I'm trying to enable tap on click (libinput_device_config_tap_set_enabled) and my first guess is that I need to configure this with udev rules? Or is there any way to do this via. orbment configuration?

Best regards,
Jonas

**Comment by Cloudef** [comment]
No, I do not expose device configuration yet in wlc.
Related: #89, #43, https://github.com/Cloudef/wlc/issues/6

**Comment by onny** [comment]
Oh sorry for opening a duplicate issue :( So there's no workaround for this issue now?

**Comment by Cloudef** [comment]
Not right now. As far I'm aware this configuration needs to be supported by the applications using libinput. (compositor in this case)

**Comment by Cloudef** [comment]
core-input was introduced for input device configuration. For option see: https://github.com/Cloudef/orbment/blob/master/plugins/core-input/core-input.c#L35-L96
