### ISSUE TITLE
GTK3 popup menus do not open

### ISSUE THREAD

**Issue by onny** [Cloudef/orbment#107]
I'm unable to open GTK3 popup menus, see this screenshot (taken from gedit):
![orbment-2015-05-18t06 43 46z](https://cloud.githubusercontent.com/assets/757752/7675551/516c3460-fd29-11e4-874c-4b03255cabeb.png)

**Comment by onny** [comment]
To be more precise, this bug is still present with `gtk3-3.16.4` and `wayland-1.8.0`

**Comment by Cloudef** [comment]
The popups here probably use subsurfaces which are not yet implemented in wlc.

**Comment by ids1024** [comment]
This is fixed now, and can be closed, right?

Same with #101 I believe.
