### ISSUE TITLE
move apps with title bar in drm backend  

### ISSUE THREAD

**Issue by athrungithub** [Cloudef/orbment#110]
Thank you.
for example, grab title bar and move weston-terminal ( termite, gnome-terminal etc) 
the pointer mouse no sync with surface, if move top or left. Down or rigth it ok.
With X11 backend it ok.
 
wlc no set window geometry. It problem is xdg-shell or surface?

**Comment by Earnestly** [comment]
What's happening is that any movement to the top-left corner of the screen when
dragging results in the mouse pointer becoming decoupled with the drag point,
while moving down-right keeps it fixed in place.
