### ISSUE TITLE
Regression: Bmenu no longer fills to fit width of monitor.

### ISSUE THREAD

**Issue by Earnestly** [Cloudef/orbment#111]
This issue has crept up again.  Bmenu no longer expands to fit the width of
the monitor it's called on.

Conversely under x11, bemenu will expand beyond the edge of the window it sits
in.

**Comment by Cloudef** [comment]
>Under x11
Does this mean when running Orbment inside X11 and bemenu inside it?
In that case, Orbment actually reports your real screen resolution instead of the window resolution as output. I don't think I have done that more properly yet.

**Comment by Earnestly** [comment]
The latter is when running orbment inside Xorg, the former is when running from a tty.
