### ISSUE TITLE
Mouse actions on dimmed surface act on surface in other space

### ISSUE THREAD

**Issue by upwhere** [Cloudef/orbment#124]
Example setup:
 - surface running browser on space mod-1, active as it's the only surface in that space
 - two surfaces running shells on space mod-2, so that one is active and one dimmed

When I switch from space mod-1 to space mod-2 and mouse over the inactive surface, I can still click links in the browser, even though it looks like I'm clicking on a terminal.

The pointer icon even changes to the 'hand' pointer to indicate there's something to click just like in the browser. If I make a motion to "select" text in that dimmed terminal and drag it, the text my browser was displaying appears and is dragged over the terminals.

Doesn't matter if it's native wayland surfaces or an xwayland surfaces or any combination.
Clicking might even deactivate all the surfaces on this space so that a lot of the keybindings don't seem to work.

The behaviour I expected from mousing a dimmed surface is for that surface to become the active one.

**Comment by s0liddi** [comment]
This even happens when space 1 is empty and space 2 has an terminal open, You can mark text in space 2 from space 1.

**Comment by Cloudef** [comment]
Fixed in latest wlc.
