### ISSUE TITLE
Bug: Loss of connectivity when switching workspace

### ISSUE THREAD

**Issue by Kinokoio** [Cloudef/orbment#129]
When you have a program that continually downloads/uploads in a workspace that is not unfocused there is a loss of connectivity 5-10 minutes of not switching to that workspace.

Steps to reproduce:
1. Start a big download or an IRC client in a workspace
2. Switch to another worskpace
3. Wait about 10 minutes
4. Switch to the download or IRC client workspace

If not a wlc/orbment issue, then I will report it as a Wayland bug.

**Comment by Cloudef** [comment]
Which program is this? Most likely the program doesn't work when it's not receiving frame callbacks or it relies on eglSwapBuffers which will cause program to freeze and wait for frame callback unless eglSwapInterval is set to 0.

**Comment by Kinokoio** [comment]
It's qterminal from the AUR

**Comment by Kinokoio** [comment]
Tested with rxvt. It was not reproduceable.

**Comment by Cloudef** [comment]
You probably should fill bug on Qt.
