### ISSUE TITLE
check xkb_state_led

### ISSUE THREAD

**Issue by sharethewisdom** [Cloudef/orbment#131]
Sould the LED indicators be working using orbment? 
Cloudef/wlc#6
If not, could someone provide some guidance for checking [xkb_state](http://xkbcommon.org/doc/current/group__state.html#gaa5a02e6f26ccd29b95e32d6fcb8f8149) using wlc?

**Comment by Earnestly** [comment]
Does this help at all? https://github.com/Earnestly/wlc_doc/blob/master/core/interface/wlc_interface.keyboard.3

**Comment by Cloudef** [comment]
The led bits are also exposed by wlc inside the wlc_modifiers. However wlc should hande the light states.

**Comment by Cloudef** [comment]
https://github.com/Cloudef/wlc/pull/101 Should be fixed by this PR
