### ISSUE TITLE
Immediate crash when opening weston-terminal

### ISSUE THREAD

**Issue by alive4ever** [Cloudef/orbment#143]
After wlc [commit f4ff049](https://github.com/Cloudef/wlc/commit/f4ff049cc30242eec9f33af7129d2e2a2865fb5a), orbment crashes immediately when attempting to run `weston-terminal`.

Additional information: weston 1.12, wayland 1.12, wayland-protocols 1.7

**Comment by Cloudef** [comment]
https://github.com/Cloudef/wlc/commit/203eddde8ea55438629f02005eca025a34917b41 Does this fix it for you?

**Comment by alive4ever** [comment]
Thanks for quick fix. Latest wlc commit fixes the issue for me.

**Comment by alive4ever** [comment]
On Fri, Oct 21, 2016 at 12:42:00AM -0700, Jari Vetoniemi wrote:

> https://github.com/Cloudef/wlc/commit/203eddde8ea55438629f02005eca025a34917b41 Does this fix it for you?

Thanks for quick fix. The commit fixes the problem for me.
