### ISSUE TITLE
Toggle or disable touchpad.

### ISSUE THREAD

**Issue by Earnestly** [Cloudef/orbment#43]
Recent commits to libinput let us disable touchpad events which would prevent accidental activation from the edge of the thumb or palm.

Also touchpads are annoying to me :-)

**Comment by Cloudef** [comment]
Try with latest commit in wlc and libinput from this branch: https://github.com/whot/libinput/tree/wip/touchpad-hover-finger

**Comment by Cloudef** [comment]
core-input was introduced for input device configuration. For options see: https://github.com/Cloudef/orbment/blob/master/plugins/core-input/core-input.c#L35-L96
