### ISSUE TITLE
Autostarts

### ISSUE THREAD

**Issue by fgaz** [Cloudef/orbment#57]
It would be nice to have a `.loliwm_autostart` file where to put commands that need to be executed when loliwm has started. Kind of like `.xinitrc` for X.

**Comment by Earnestly** [comment]
No more dotfiles, please.

**Comment by Cloudef** [comment]
Configurations provided by "configuration plugin" would be in $XDG_CONFIG_HOME/{wmname}/ for user configuration and /etc/{wmname}/ for system-wide configuration.

**Comment by aidanholm** [comment]
@fgaz There's a pull request currently pending that, when merged, will let you specify autostart commands under an [autostart] section in $XDG_CONFIG_HOME/orbment/orbment.ini; that should land sometime in the next few days.

**Comment by aidanholm** [comment]
@fgaz Merged.
