### ISSUE TITLE
loliwm crashes on Terminal

### ISSUE THREAD

**Issue by paulhandy** [Cloudef/orbment#68]
It works fine on my Thinkpad, but on Dell Precision the log shows the error:

>Date: 2015-03-12 MDT
>[16:08:20.749] Doing work on SUID/SGID side and dropping permissions
>[16:08:20.749] Work done, dropping permissions and checking communication
>[16:08:20.756] become active
>[16:08:20.764] (WARN) Failed to open X11 display
>[16:08:20.811] Closed drm
>[16:08:20.811] (WARN) Could not initialize any backend
>could not connect to wayland server
>(EE) 
>Fatal server error:
>(EE) Couldn't add screen
>(EE) 
>[16:08:20.812] Parent exit (3646)
>[16:08:20.812] Restoring tty 0
>[16:08:20.948] Cleanup wlc

I thought perhaps it could be my nvidia graphics driver (using nouveau), but weston-launch works properly. So, I'm not exactly sure what the issue is here.

**Comment by Cloudef** [comment]
Do you have /dev/dri/card0? drm backend right now is hardcoded to that.
Also, you could try with the feature/plugins branch which is quite bit ahead, just remember to compile it with -DCMAKE_BUILD_TYPE=Debug and -DSOURCE_WLC=ON (to build wlc from source as well). If you have logind, you do not need to SUID or SGID the binary on that branch.

**Comment by paulhandy** [comment]
I have /dev/dri/card0 and card1, but I believe that card1 is the default display set by BIOS. Perhaps this problem is a little bit lower than loliwm, and more on the driver side of my problems.

**Comment by Cloudef** [comment]
According to log, it doesn't even try opening any card thoug. Make sure you have no DISPLAY env variable set in TTY.

**Comment by Cloudef** [comment]
Was this solved?

**Comment by paulhandy** [comment]
It works if I use card0, yes. Perhaps in a future version, card selection
could be a feature?

**Comment by Cloudef** [comment]
Yeah, I have issue for that here: https://github.com/Cloudef/wlc/issues/11

**Comment by Cloudef** [comment]
You can now change device with WLC_DRM_DEVICE env variable (default card0), I'll later make it autodetect primary device as default.
