### ISSUE TITLE
Firefox’ autocompletion and tooltips put it behind any fullscreen surface

### ISSUE THREAD

**Issue by linkmauve** [Cloudef/orbment#70]
It first creates a new surface in which to draw the menu/tooltip, which is considered a normal window, so this surface steals the focus from Firefox’ main window, and since another window is fullscreen Firefox goes behind it, which removes the menu/tooltip window.

**Comment by Cloudef** [comment]
Apparently fixed by fixing the focus race condition for Xwayland clients.

**Comment by Cloudef** [comment]
And reproduced :)
