### ISSUE TITLE
Sometimes, Firefox renders only half of its surface width, with borders on both sides

### ISSUE THREAD

**Issue by linkmauve** [Cloudef/orbment#73]
It behaves exactly as if it was stacked to the left side, except centered and with black borders on the left and on the right. In this state it works fine, but only forcing a resize would make it recover, switching windows doesn’t.
I’m not sure how to reproduce this one, it looks quite racy.

**Comment by ld-cd** [comment]
This is caused when it closes with a window open next to it so its at half
size. To fix just hit mod+f twice to put it into and take it out of
fullscreen

**Comment by linkmauve** [comment]
If its non-fullscreen surface size is the same as its fullscreen one, mod+f doesn’t fix that issue.

**Comment by ld-cd** [comment]
I think your right, but right now I can't get firefox to display wrong so I
can't confirm

If its non-fullscreen surface size is the same as its fullscreen one, mod+f
doesn’t fix that issue.

—
Reply to this email directly or view it on GitHub
<https://github.com/Cloudef/loliwm/issues/73#issuecomment-82694954>.

**Comment by Cloudef** [comment]
This is caused by wlc rendering with different size that client has buffer for.
Most likely resize isn't commited correctly. (States like these are double buffered)

**Comment by Cloudef** [comment]
Bemenu appearing was related to #71, this is most likely different issue.
