### ISSUE TITLE
When a shell_surface is made fullscreen on another output, keyboard focus switch is disabled

### ISSUE THREAD

**Issue by linkmauve** [Cloudef/orbment#80]
I can still click on the dimmed terminal and everything works fine after that.

**Comment by Cloudef** [comment]
If the surface was focused, focus moves with the output. Or this is how it should be, I haven't actually tested :)

**Comment by linkmauve** [comment]
I forgot to update that issue after testing a bit more; the issue is actually that putting a wl_shell_surface on another output than the one currently used will move keyboard input to that output, but not mouse input.
