### ISSUE TITLE
Improvements from weston

### ISSUE THREAD

**Issue by podhorsky-ksj** [Cloudef/orbment#89]
Hello,

will be there also some improvements from weston like:
[keyboard]
keymap_options=grp:alt_shift_toogle
keymap_layout

[libinput]
enable_tap=true

Also, from where takes bemenu the commands? Aliases, which I use for bash environment don't work. Where should I put them to?

Thanks for this very nice compositor.

**Comment by Cloudef** [comment]
The default bemenu-run just looks at $PATH, it does not use shell at all.
You need to create custom launcher script that also outputs aliases and pipe that to bemenu.

@aidanholm Has been working on the .ini configuration. It currently only allows modifying of the keybindings however.

**Comment by Earnestly** [comment]
For the time being you can easily define custom keyboard options and layouts
via the `XKB_DEFAULT_*` environment variables, such as:

```bash
export XKB_DEFAULT_LAYOUT=gb
export XKB_DEFAULT_OPTIONS=compose:ralt,ctrl:nocaps

export XKB_DEFAULT_VARIANT=...
export XKB_DEFAULT_RULES=...
export XKB_DEFAULT_MODEL=...
```

**Comment by podhorsky-ksj** [comment]
Thanks, defining these variables before run orbment work, even switching to another keyboard layout with grp:alt_shift_toogle.

Is there something similar for libinput (for touchpad tap option)?

**Comment by Cloudef** [comment]
Nope, I don't expose yet libinput configuration.

**Comment by Cloudef** [comment]
core-input was introduced for input device configuration. For options see: https://github.com/Cloudef/orbment/blob/master/plugins/core-input/core-input.c#L35-L96

**Comment by podhorsky-ksj** [comment]
That's nice, thanks.
But I can't still find, how looks config file and how this config file can be loaded by orbment.

**Comment by Cloudef** [comment]
First run orbment with --log option set to file.
Observe the log for following strings

```
[09:40:50.625] core-input: Configuring input device: MOSART Semi. 2.4G Keyboard Mouse (event0) (16641-1578)
[09:40:50.625] core-input: Configuring input device: MOSART Semi. 2.4G Keyboard Mouse (event1) (16641-1578)
[09:40:50.625] core-input: Configuring input device: Wacom Intuos Pro S Finger (event8) (788-1386)
[09:40:50.625] core-input: Configuring input device: Metadot - Das Keyboard Das Keyboard (event2) (320-9456)
[09:40:50.625] core-input: Configuring input device: Metadot - Das Keyboard Das Keyboard (event3) (320-9456)
```

Write down the numbers at end for devices you want to configure.

Next create config file at ```${XDG_CONFIG_HOME:~/.config}/orbment/orbment.ini```

```
[input-16641-1578]
# sets mouse accel to full
accel = 1

# enables "natural scroll"
natural-scroll = true

# etc ...
```
